<%@ Page Language="VB" AutoEventWireup="false" CodeFile="DetailsViewMultiRow.aspx.vb" Inherits="DetailsViewMultiRow" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title>DetailsView Page</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:SqlDataSource ID="dsCustomers" runat="server" ConnectionString="<%$ ConnectionStrings:AWLTConnection %>"
            SelectCommand="SELECT * FROM [SalesLT].[Customer]" />
        <asp:DetailsView ID="CustomerDetails" runat="server" DataSourceID="dsCustomers" AllowPaging="True"
            EmptyDataText="No data was found" DataKeyNames="CustomerID,RowGuid" EnablePagingCallbacks="True"
            PageIndex="5" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px"
            CellPadding="3" ForeColor="Black" GridLines="Vertical" 
            Caption="This is the caption" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" AutoGenerateInsertButton="True">
            <HeaderTemplate>
                This is the header row
            </HeaderTemplate>
            <FooterTemplate>
                This is the footer row
            </FooterTemplate>
            <PagerSettings PageButtonCount="20" Position="TopAndBottom" />
            <FooterStyle BackColor="#CCCCCC" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <FieldHeaderStyle Font-Bold="true" Font-Names="Arial Black" Font-Size="Larger" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <EditRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <AlternatingRowStyle BackColor="#CCCCCC" />
        </asp:DetailsView>
        <p>
            <asp:Label runat="server" ID="lblInfo" />
        </p>
    </div>
    </form>
</body>
</html>